export interface PortfolioItem {
  id: string;
  category: 'banners' | 'social' | 'packaging' | 'video' | 'flyers' | 'eblast' | 'magazine';
  thumbnail: string;
  image: string;
  client?: string;
  tags: string[];
  title: string;
  hoverText?: string;
  icon?: string; // Optional icon for special types
  video?: boolean;
  pdf?: boolean;
  iframeUrl?: string; // For HTML5 interactive banners
}

// Base paths
const O = '/portfolio/optimized';

export const portfolioItems: PortfolioItem[] = [

  // ══ VIDEO ══════════════════════════════════════════════════════════════════
  {
    id: 'v-now-forever',
    category: 'video',
    thumbnail: `${O}/video/video2.gif`,
    image: `${O}/video/Now and Forever.mp4`,
    client: 'Now and Forever',
    tags: ['Video', 'Motion Graphics'],
    title: 'Now and Forever',
    video: true,
  },
  {
    id: 'v-anniversaries',
    category: 'video',
    thumbnail: `${O}/video/video2.gif`,
    image: `${O}/video/June - Anniversaries 1Y.mp4`,
    client: 'Goodwill',
    tags: ['Video', 'Corporate'],
    title: 'Anniversaries – 1 Year',
    video: true,
  },
  {
    id: 'v-greg',
    category: 'video',
    thumbnail: `${O}/video/video2.gif`,
    image: `${O}/video/Greg April Video.mp4`,
    client: 'Greg April',
    tags: ['Video', 'Promotional'],
    title: 'Greg April Video',
    video: true,
  },

  // ══ ANIMATED GIFs ══════════════════════════════════════════════════════════
  {
    id: 's-dfw-christmas',
    category: 'social',
    thumbnail: `${O}/social/DFW_Christmas_600x600.gif`,
    image: `${O}/social/DFW_Christmas_600x600.gif`,
    client: 'DFW Airport',
    tags: ['GIF', 'Animation', 'Social'],
    title: 'DFW Christmas Campaign',
  },
  {
    id: 's-google-pm',
    category: 'social',
    thumbnail: `${O}/social/Google_Project_Management_Professional.gif`,
    image: `${O}/social/Google_Project_Management_Professional.gif`,
    client: 'Goodwill Dallas',
    tags: ['GIF', 'Animation', 'Social'],
    title: 'Google PM Certification',
  },

  {
    id: 's-ms-word',
    category: 'social',
    thumbnail: `${O}/social/Microsoft_Word.gif`,
    image: `${O}/social/Microsoft_Word.gif`,
    client: 'Goodwill Dallas',
    tags: ['GIF', 'Animation', 'Social'],
    title: 'Microsoft Word Tips',
  },
  {
    id: 's-comptia',
    category: 'social',
    thumbnail: `${O}/social/Virtual_Comptia.gif`,
    image: `${O}/social/Virtual_Comptia.gif`,
    client: 'Goodwill Dallas',
    tags: ['GIF', 'Animation', 'Social'],
    title: 'Virtual CompTIA',
  },
  {
    id: 's-post3',
    category: 'social',
    thumbnail: `${O}/social/post3.gif`,
    image: `${O}/social/post3.gif`,
    client: 'Goodwill Dallas',
    tags: ['GIF', 'Animation', 'Social'],
    title: 'Google Project Management',
  },

  // ══ STATIC SOCIAL POSTS ════════════════════════════════════════════════════
  {
    id: 's-23',
    category: 'social',
    thumbnail: `${O}/social/23.png`,
    image: `${O}/social/23.png`,
    tags: ['Social', 'Design'],
    title: 'Creative Post Design',
  },
  {
    id: 's-24',
    category: 'social',
    thumbnail: `${O}/social/24.png`,
    image: `${O}/social/24.png`,
    tags: ['Social', 'Design'],
    title: 'Brand Post Design',
  },
  {
    id: 's-career-aug16',
    category: 'social',
    thumbnail: `${O}/social/Career_Services_AUG_16.jpg`,
    image: `${O}/social/Career_Services_AUG_16.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Career Services'],
    title: 'Career Services – Aug 16',
  },
  {
    id: 's-career-aug19',
    category: 'social',
    thumbnail: `${O}/social/CareerServicesPost_AUG_19.jpg`,
    image: `${O}/social/CareerServicesPost_AUG_19.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Career Services'],
    title: 'Career Services – Aug 19',
  },
  {
    id: 's-career-aug22',
    category: 'social',
    thumbnail: `${O}/social/Career Services post_AUG_22.jpg`,
    image: `${O}/social/Career Services post_AUG_22.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Career Services'],
    title: 'Career Services – Aug 22',
  },
  {
    id: 's-career-sep2',
    category: 'social',
    thumbnail: `${O}/social/CareerServices_SEP_2.jpg`,
    image: `${O}/social/CareerServices_SEP_2.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Career Services'],
    title: 'Career Services – Sep 2',
  },
  {
    id: 's-career-sep27',
    category: 'social',
    thumbnail: `${O}/social/CareerServices_SEP_27.jpg`,
    image: `${O}/social/CareerServices_SEP_27.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Career Services'],
    title: 'Career Services – Sep 27',
  },
  {
    id: 's-google-it',
    category: 'social',
    thumbnail: `${O}/social/Google_IT_Support _AUG_25.jpg`,
    image: `${O}/social/Google_IT_Support _AUG_25.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Education'],
    title: 'Google IT Support',
  },
  {
    id: 's-lyft-aug23',
    category: 'social',
    thumbnail: `${O}/social/Lyft services_AUG_23.jpg`,
    image: `${O}/social/Lyft services_AUG_23.jpg`,
    client: 'Lyft',
    tags: ['Social', 'Promotion'],
    title: 'Lyft Services – Aug 23',
  },
  {
    id: 's-lyft-aug31',
    category: 'social',
    thumbnail: `${O}/social/Lyft services_AUG_31.jpg`,
    image: `${O}/social/Lyft services_AUG_31.jpg`,
    client: 'Lyft',
    tags: ['Social', 'Promotion'],
    title: 'Lyft Services – Aug 31',
  },
  {
    id: 's-lyft-sep4',
    category: 'social',
    thumbnail: `${O}/social/Lyft_Sep_4.jpg`,
    image: `${O}/social/Lyft_Sep_4.jpg`,
    client: 'Lyft',
    tags: ['Social', 'Promotion'],
    title: 'Lyft Services – Sep 4',
  },
  {
    id: 's-dfw-arabic',
    category: 'social',
    thumbnail: `${O}/social/DFW_Translation_Arabic.jpg`,
    image: `${O}/social/DFW_Translation_Arabic.jpg`,
    client: 'DFW Airport',
    tags: ['Social', 'Multilingual'],
    title: 'DFW – Arabic Translation',
  },
  {
    id: 's-dfw-farsi',
    category: 'social',
    thumbnail: `${O}/social/DFW_Translation_Farsi.jpg`,
    image: `${O}/social/DFW_Translation_Farsi.jpg`,
    client: 'DFW Airport',
    tags: ['Social', 'Multilingual'],
    title: 'DFW – Farsi Translation',
  },
  {
    id: 's-resume',
    category: 'social',
    thumbnail: `${O}/social/ResumeBuilding_SEP_1.jpg`,
    image: `${O}/social/ResumeBuilding_SEP_1.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Education'],
    title: 'Resume Building Workshop',
  },
  {
    id: 's-interview-sep1',
    category: 'social',
    thumbnail: `${O}/social/Interview Prep_SEP_1.jpg`,
    image: `${O}/social/Interview Prep_SEP_1.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Education'],
    title: 'Interview Prep – Sep 1',
  },
  {
    id: 's-interview-sep23',
    category: 'social',
    thumbnail: `${O}/social/InterviewPrep_SEP_23.jpg`,
    image: `${O}/social/InterviewPrep_SEP_23.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Social', 'Education'],
    title: 'Interview Prep – Sep 23',
  },

  // ══ BANNER ADS ═════════════════════════════════════════════════════════════
  {
    id: 'b-steak-express',
    category: 'banners',
    thumbnail: `${O}/banners/steak-express/300x250.jpg`,
    image: `${O}/banners/steak-express/300x250.jpg`,
    iframeUrl: `${O}/banners/steak-express/index.html`,
    client: 'Steak Express',
    tags: ['Banner', 'HTML5', 'Interactive'],
    title: 'Interactive Steak Express Banner',
  },
  {
    id: 'b-sacmc',
    category: 'banners',
    thumbnail: `${O}/banners/sacmc/300x600.jpg`,
    image: `${O}/banners/sacmc/300x600.jpg`,
    iframeUrl: `${O}/banners/sacmc/index1.html`,
    client: 'SACMC',
    tags: ['Banner', 'HTML5', 'Interactive'],
    title: 'SACMC Medical Center Banner',
  },
  {
    id: 'b-enertel',
    category: 'banners',
    thumbnail: `${O}/banners/enertel/300x600.jpg`,
    image: `${O}/banners/enertel/300x600.jpg`,
    iframeUrl: `${O}/banners/enertel/index3.html`,
    client: 'Ener-Tel',
    tags: ['Banner', 'HTML5', 'Interactive'],
    title: 'Ener-Tel Security Banner',
  },
  {
    id: 'b-collection-cover',
    category: 'banners',
    thumbnail: `${O}/banners/Coverpage.jpg`,
    image: `${O}/banners/Coverpage.jpg`,
    client: 'Various Clients',
    tags: ['Collection', 'Digital', 'Portfolio'],
    title: 'Banner Ad Design Collection',
  },
  {
    id: 'b-dfw-memorial',
    category: 'banners',
    thumbnail: `${O}/banners/banner1.jpg`,
    image: `${O}/banners/banner1.jpg`,
    client: 'DFW Airport',
    tags: ['Banner', 'HTML5', 'Digital'],
    title: 'DFW Memorial Day Banner',
  },
  {
    id: 'b-dfw-digital',
    category: 'banners',
    thumbnail: `${O}/banners/DD.jpg`,
    image: `${O}/banners/DD.jpg`,
    client: 'DFW Airport',
    tags: ['Banner', 'Digital', 'Ad'],
    title: 'DFW Digital Advertisement',
  },
  {
    id: 'b-dfw-mobile-ad',
    category: 'banners',
    thumbnail: `${O}/banners/d.jpg`,
    image: `${O}/banners/d.jpg`,
    client: 'DFW Airport',
    tags: ['Banner', 'Mobile', 'Ad'],
    title: 'DFW Mobile Banner Ad',
  },


  {
    id: 'b-grand-city',
    category: 'banners',
    thumbnail: `${O}/banners/hoarding.jpg`,
    image: `${O}/banners/hoarding.jpg`,
    client: 'Grand City',
    tags: ['Outdoor', 'Print', 'Hoarding'],
    title: 'Grand City Hoarding (30×20ft)',
  },

  // ══ PACKAGING / BRANDING ═══════════════════════════════════════════════════
  {
    id: 'p-tea',
    category: 'packaging',
    thumbnail: `${O}/packaging/Tea Pack Design_2 copy.jpg`,
    image: `${O}/packaging/Tea Pack Design_2 copy.jpg`,
    client: 'Tea Brand',
    tags: ['Packaging', 'Branding'],
    title: 'Tea Pack Design',
  },
  {
    id: 'p-ewj',
    category: 'packaging',
    thumbnail: `${O}/packaging/EWJ 1ltr Front + Side + Top.jpg`,
    image: `${O}/packaging/EWJ 1ltr Front + Side + Top.jpg`,
    client: 'EWJ',
    tags: ['Packaging', 'Branding', '3-Side'],
    title: 'EWJ 1L Bottle Packaging',
  },
  {
    id: 'p-kaizen',
    category: 'packaging',
    thumbnail: `${O}/packaging/Kaizen Poster.jpg`,
    image: `${O}/packaging/Kaizen Poster.jpg`,
    client: 'Kaizen',
    tags: ['Branding', 'Poster'],
    title: 'Kaizen Poster',
  },
  {
    id: 'p-oxigen',
    category: 'packaging',
    thumbnail: `${O}/packaging/Standee_Oxigen_09-09-2015.jpg`,
    image: `${O}/packaging/Standee_Oxigen_09-09-2015.jpg`,
    client: 'Oxigen',
    tags: ['Standee', 'Branding', 'Retail'],
    title: 'Oxigen Wallet Standee',
  },
  {
    id: 'p-standee-all',
    category: 'packaging',
    thumbnail: `${O}/packaging/Standee All Projects_2 14-06-17.jpg`,
    image: `${O}/packaging/Standee All Projects_2 14-06-17.jpg`,
    tags: ['Standee', 'Multi-Brand'],
    title: 'Multi-Project Standees',
  },
  {
    id: 'p-pkg3',
    category: 'packaging',
    thumbnail: `${O}/packaging/6 (1).jpg`,
    image: `${O}/packaging/6 (1).jpg`,
    tags: ['Packaging', 'Branding'],
    title: 'Product Packaging Design',
  },

  // ══ FLYERS / PRINT ═════════════════════════════════════════════════════════
  {
    id: 'f-bbq',
    category: 'flyers',
    thumbnail: `${O}/flyers/ThepitBBQ_Menu.png`,
    image: `${O}/flyers/ThepitBBQ_Menu.png`,
    client: 'The Pit BBQ',
    tags: ['Menu', 'Print', 'Restaurant'],
    title: 'The Pit BBQ – Menu Design',
  },
  {
    id: 'f-digital-skills',
    category: 'flyers',
    thumbnail: '',
    image: `${O}/flyers/Digital Skills Brochure.pdf`,
    client: 'Goodwill Dallas',
    tags: ['Print', 'Brochure', 'PDF'],
    title: 'Digital Skills Brochure',
    pdf: true,
  },

  {
    id: 'f-naf-print',
    category: 'flyers',
    thumbnail: '',
    image: `${O}/flyers/Now and Forever.pdf`,
    client: 'Now and Forever',
    tags: ['Print', 'Collateral', 'PDF'],
    title: 'Now and Forever – Print',
    pdf: true,
  },
  {
    id: 'f-goodwill-feedback',
    category: 'flyers',
    thumbnail: '',
    image: `${O}/flyers/Goodwill_02_JPFeedback.pdf`,
    client: 'Goodwill Dallas',
    tags: ['Print', 'Brand', 'PDF'],
    title: 'Goodwill Brand Collateral',
    pdf: true,
  },



  // ══ E-BLASTS ═══════════════════════════════════════════════════════════════
  {
    id: 'e-early-giving',
    category: 'eblast',
    thumbnail: `${O}/eblast/eblast1.gif`,
    image: `${O}/eblast/eblast1.gif`,
    client: 'North Texas Giving Day',
    tags: ['Email', 'E-blast', 'Animated'],
    title: 'Early Giving Campaign',
  },
  {
    id: 'e-decide-rise',
    category: 'eblast',
    thumbnail: `${O}/eblast/eblast2.gif`,
    image: `${O}/eblast/eblast2.gif`,
    client: 'Goodwill Dallas',
    tags: ['Email', 'E-blast', 'Animated'],
    title: 'Decide to Rise Campaign',
  },
  {
    id: 'e-donate',
    category: 'eblast',
    thumbnail: `${O}/eblast/donate.jpg`,
    image: `${O}/eblast/donate.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Email', 'E-blast', 'CTA'],
    title: 'Donation Drive Email',
  },


  // ══ MAGAZINE ═══════════════════════════════════════════════════════════════
  {
    id: 'm-akash-vukoti',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_Akash Vukoti.pdf`,
    client: 'Akash Vukoti',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – Akash Vukoti',
    pdf: true,
  },
  {
    id: 'm-angelo-civic',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_Angelo Civic Theatre.pdf`,
    client: 'Angelo Civic Theatre',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – Angelo Civic Theatre',
    pdf: true,
  },
  {
    id: 'm-dusty-mccoy',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_Dusty McCoy.pdf`,
    client: 'Dusty McCoy',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – Dusty McCoy',
    pdf: true,
  },
  {
    id: 'm-rene-alvarado',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_Rene Alvarado.pdf`,
    client: 'Rene Alvarado',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – Rene Alvarado',
    pdf: true,
  },
  {
    id: 'm-river-view',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_River view restaurant.pdf`,
    client: 'River View Restaurant',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – River View Restaurant',
    pdf: true,
  },
  {
    id: 'm-rogue-cafe',
    category: 'magazine',
    thumbnail: '',
    image: `${O}/magazine/Create Magazine_2019_Rogue Café.pdf`,
    client: 'Rogue Café',
    tags: ['Magazine', 'Print', 'PDF'],
    title: 'Create Magazine – Rogue Café',
    pdf: true,
  },

  {
    id: 'm-awareness',
    category: 'magazine',
    thumbnail: `${O}/magazine/mag2.jpg`,
    image: `${O}/magazine/mag2.jpg`,
    client: 'Goodwill Dallas',
    tags: ['Magazine', 'Print', 'Ad'],
    title: 'Awareness Campaign Ad',
  },
];
